---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-session
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: spring-session
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
        - name: web
          image: alexandreroman/spring-session-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 10
            failureThreshold: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: spring-session
spec:
  replicas: 1
  selector:
    matchLabels:
      role: redis
  template:
    metadata:
      labels:
        role: redis
    spec:
      containers:
        - name: redis
          image: redis:5
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: spring-session-lb
  labels:
    app: spring-session
  namespace: spring-session
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    role: web
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: spring-session
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  selector:
    role: redis
